import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: "#f4f6f7",
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 40,
    marginBottom: 15,
    color: "#1e272e",
    letterSpacing: 1.2,
  },
  dropdownContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 25,
  },
  dropdown: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 14,
    marginHorizontal: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#bdc3c7",
    shadowColor: "#bdc3c7",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  dropdownText: {
    fontSize: 18,
    color: "#34495e",
    fontWeight: "600",
  },
  placeItem: {
    backgroundColor: "#ffffff",
    padding: 20,
    borderRadius: 16,
    marginBottom: 15,
    shadowColor: "#2c3e50",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  placeName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2980b9",
    marginBottom: 5,
  },
  placeAddress: {
    fontSize: 16,
    color: "#7f8c8d",
  },
  favoritesButton: {
    backgroundColor: "#f39c12",
    padding: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#f39c12",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  favoritesButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  loadingIndicator: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    width: "80%",
    maxHeight: "60%",
    elevation: 10,
  },
  modalItem: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#dcdcdc",
  },
  modalText: {
    fontSize: 18,
    color: "#2c3e50",
    textAlign: "center",
  },
  closeButton: {
    marginTop: 15,
    backgroundColor: "#e74c3c",
    padding: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  closeButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  searchInput: {
    height: 45,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 12,
    paddingLeft: 12,
    marginBottom: 20,
    backgroundColor: "#fff",
    shadowColor: "#bdc3c7",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
});
