import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#f8f9fa",
  },
  title: {
    fontSize: 34,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#1e272e",
    letterSpacing: 1.2,
  },
  detail: {
    fontSize: 18,
    marginBottom: 12,
    color: "#485460",
    lineHeight: 24,
  },
  favoriteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    marginTop: 20,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
    transition: "all 0.3s ease-in-out",
  },
  addButton: {
    backgroundColor: "#0abde3",
    shadowColor: "#0abde3",
  },
  removeButton: {
    backgroundColor: "#ee5253",
    shadowColor: "#ee5253",
  },
  favoriteButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 12,
  },
  websiteButton: {
    backgroundColor: "#ff9f43",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 15,
    shadowColor: "#ff9f43",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
    transform: [{ scale: 1 }],
    transition: "transform 0.3s ease-in-out",
  },
  websiteButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  subTitle: {
    fontSize: 22,
    fontWeight: "700",
    marginTop: 25,
    marginBottom: 15,
    color: "#1e272e",
  },
  interactiveCard: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
    marginBottom: 20,
    transform: [{ scale: 1 }],
    transition: "transform 0.3s ease-in-out",
  },
});
